name: default

on: [push, pull_request]

jobs:
  format:
    name: Run StyLua
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: 0.17.0
        args: --check .
